name: CML

on: [pull_request]

jobs:
  dvc:
    runs-on: ubuntu-latest
    container: docker://dvcorg/dvc-cml:latest

    steps:
      - uses: actions/checkout@v2
      
      - name: dvc_action_run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DVC_PULL: ""
        run: |
          apt-get update
          apt-get install -y python3 python3-pip
          pip3 install --upgrade pip
          alias python=/usr/local/bin/python3
          echo "alias python=/usr/local/bin/python3" >> ~/.bashrc
          #pip3 install dvc
          test -f requirements.txt && pip3 install -r requirements.txt
          python -V
          pip list | grep tensorflow
          #echo "============= TRAIN ============="
          #python train.py
          dvc repro version.dvc
          echo "============= RUN CML ============="
          dvc_cml_run

