name: CML

on: [pull_request]

jobs:
  dvc:
    runs-on: ubuntu-latest
    container: docker://dvcorg/dvc-cml:latest

    steps:
      - uses: actions/checkout@v2
      
      - name: dvc_action_run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DVC_PULL: ""
        run: |
          apt-get update && apt-get install -y python-pip
          pip install --upgrade pip
          pip install -r requirements.txt
          dvc_cml_run

