name: CML

on: [push]

jobs:
  dvc:
    runs-on: ubuntu-latest
    container: docker://dvcorg/dvc-cml-py3:latest

    steps:
      - uses: actions/checkout@v2
      
      - name: dvc_action_run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DVC_PULL: "-"
        run: |
          apt-get install -y --no-install-recommends --fix-missing git python3-setuptools python3-dev
          git clone https://github.com/iterative/dvc/
          cd dvc && git checkout 128fa7f && pip install -U -e .[all,tests]
          cd ..
          dvc version
          test -f requirements.txt && pip3 install -r requirements.txt
          echo "============= RUN CML ============="
          dvc_cml_run

#      - name: "CML report"
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          DVC_PULL: "-"
#        run: |
#          npm install dvc
#          dvc pull
#          dvc repro
#          echo "# CML report" >> report.md
#          dvc metrics diff --show-json | cml-metrics >> report.md
#          dvc params diff --show-json | cml-params >> report.md
#          dvc plot diff --show-json | cml-plots >> report.md
#          dvc diff --show-json | cml-files >> report.md
#          dvc push
#          cml-send-report report.md


