name: CML

on: [pull_request]

jobs:
  dvc:
    runs-on: ubuntu-latest
    container: docker://dvcorg/dvc-cml:latest

    steps:
      - uses: actions/checkout@v2
      
      - name: dvc_action_run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DVC_PULL: ""
        run: |
          apt-get update
          sudo apt purge python2.x-minimal
          apt-get install -y python3 python3-pip
          pip3 install --upgrade pip
          #alias python=/usr/bin/python3.6
          #echo "alias python=/usr/bin/python3.6" >> ~/.bashrc
          #rm -rf /usr/bin/python2 /usr/bin/python
          #ln -s /usr/bin/python3.6 /usr/bin/python2
          #ln -s /usr/bin/python3.6 /usr/bin/python
          python -V
          #echo "============= TRAIN ============="
          #python train.py
          dvc repro version.dvc
          test -f requirements.txt && pip3 install -r requirements.txt
          echo "============= RUN CML ============="
          dvc_cml_run

